# Generated by Django 5.0.1 on 2024-02-12 11:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0020_remove_purchasing_invoice_remove_purchasing_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('time_to_pay', models.DateField()),
                ('done', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='static/warehouses/invoice_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('nip', models.IntegerField(blank=True, null=True)),
                ('regon', models.IntegerField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchasing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty', models.IntegerField(default=1)),
                ('prise', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_time', models.DateField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchasing.invoicein')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplieritem', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplieritem', to='warehouses.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.supplier')),
            ],
        ),
    ]
