# Generated by Django 5.0.1 on 2024-01-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_item_produce_code_alter_item_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieritem',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
