# Generated by Django 5.0.1 on 2024-01-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_number', models.CharField(max_length=50)),
                ('prise', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time_to_pay', models.DateTimeField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Purchasing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty', models.IntegerField(default=1)),
                ('prise', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_time', models.DateField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.invoicein')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.supplier')),
            ],
        ),
    ]
