# Generated by Django 5.0.1 on 2024-01-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0005_invoicein_purchasing'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicein',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='invoice_attachments/'),
        ),
    ]
