# Generated by Django 5.0.1 on 2024-01-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0006_invoicein_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicein',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoicein',
            name='time_to_pay',
            field=models.DateField(),
        ),
    ]
