# Generated by Django 5.0.1 on 2024-01-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0007_alter_invoicein_invoice_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicein',
            name='prise',
        ),
    ]
