# Generated by Django 5.0.1 on 2024-01-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0008_remove_invoicein_prise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasing',
            old_name='shipping_time',
            new_name='delivery_time',
        ),
    ]
