# Generated by Django 5.0.1 on 2024-01-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0009_rename_shipping_time_purchasing_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mysite/'),
        ),
    ]
