# Generated by Django 5.0.1 on 2024-01-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0011_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicein',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='warehouses/static/warehouses/invoice_attachments/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='warehouses/static/warehouses/items'),
        ),
    ]
