# Generated by Django 5.0.1 on 2024-02-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0012_alter_invoicein_attachment_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicein',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='static/warehouses/invoice_attachments/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/warehouses/items/'),
        ),
    ]
