# Generated by Django 5.0.1 on 2024-02-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0019_warehouse_created_at_warehouse_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasing',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchasing',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchasing',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplieritem',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplieritem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplieritem',
            name='item',
        ),
        migrations.DeleteModel(
            name='InvoiceIn',
        ),
        migrations.DeleteModel(
            name='Purchasing',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='SupplierItem',
        ),
    ]
